#%RAML 1.0
title: Dynamic Logger Controller
version: 1.0
mediaType: [application/json]
baseUri: http://localhost:8081
types:
  LoggerType: !include types/LogLevelType.raml
  UpdateMultiApp: !include types/UpdateMultiApps.raml
  LoggerConfig: !include types/LoggerConfig.raml

/loggers:
    get:     
      responses:
        200:       
          body:
            application/json:
              type: LoggerType
              example : !include examples/LogLevelExample.raml
    put:
      description: |
        Update log levels for application in given collection
      body:
        application/json:
          type: UpdateMultiApp[]
          example : !include examples/LogLevelUpdateMultiApps.raml
      responses:
        200:
          description: |
            Succesfully updated the resource
          body:
            application/json: 

    /{appName}:
      uriParameters:
        appName:
          description: application name to update log level
      get:
        description: |
          Given App log info
        responses:
          200:
            body:
              application/json:
                type: LoggerType
                example : !include examples/LogLevelExample.raml
      put:
        description: |
          Update specific log level for given application name
        body:
          application/json:
            type: LoggerConfig[]
            example : !include examples/LogLevelUpdateOneApp.raml
        responses:
          200:
            body:
              application/json:
                type: LoggerType
                example : !include examples/LogLevelExample.raml
      post:
        description: |
          Add new logger to an existing appliction
        body:
          application/json:
            type: LoggerConfig[]
            example : !include examples/LogLevelUpdateOneApp.raml
        responses:
          200:
            body:
              application/json:
                type: LoggerType
                example : !include examples/LogLevelExample.raml                